meta:
  random_seed: 0
  samplerate: 20000
  duration: 10

randgrid:
  space:
    origin: [0, 0]
    grid: [2, 2]
    shape: "square"
    spacing: 0.5
    limits: [-1, 1, -1, 1]
  time:
    duration: 1200
    samplerate: 20000
    track_samplerate: 3
  fish:
    species: "fakefish"
    nfish: [5, 8]
    nchirps: [10, 50]
    nrises: [5, 10]
  outpath: "../../simulations/randgrid"

species:
  sine: "Sinewave"
  fakefish: "Apteronotus leptorhynchus-inspired EOD with random chirps and rises"
  alepto: "Apteronotus leptorhynchus"
  arostratus: "Apteronotus rostratus"
  eigenmannia: "Eigenmannia virescens"
  sternarchella: "Sternarchella terminalis"
  sternopygus: "Sternopygus macrurus"

fish:
  fakefish:
    eod:
      frequency: [400, 1200]
      harmonics:
        amplitudes: [0.90062, 0.15311, 0.072049, 0.012609, 0.011708]
        phases: [1.3623, 2.3246, 0.9869, 2.6492, -2.6885]
      phase0: 0
      noise_std: 0.01
      chirp:
        sizes: [60, 200]
        durations: [0.01, 0.08]
        kurtosis: [1, 2]
        contrasts: [0.2, 1.0]
        undershoots: [0.0, 0.01]
      rise:
        sizes: [10, 100]
        rise_tau: [0.005, 0.1]
        decay_tau: [1, 15]
    body:
      size: [0.05, 0.25]
    movement:
      forward_s: 0.2
      backward_s: 0.1
      backward_h: 0.01
      mode_veloc: 0.2
      max_veloc: 1

